micronaut:
  application:
    name: rabbitmqApp
rabbitmq:
  uri: amqp://localhost:5672
  virtual-host: /
  username: guest
  password: guest
  bindings:
    queue-name-a:
      exchange: queue-name-a
      queue: queue-name-a
      dlq: false
      retry: true








